soft:
    - "блять->билять"
    - "сука->baka"
    - "чурка->чуфка"
    - "таджик->baka"
    - "гандон->ганфдон"
    - "пиздец->пипец"
    - "сперма->молочко"
    - "пизда->киска"
    - "?->..?"
soft-symbols:
  - "р->л"
  - "о->ё"

start:
  - "Эххь.. "
  - "Err.. "
  - "Ehh... "
  - "Eh?! "
  - "РРР! "
  - ""
  - ""
ends:
  - " бака!"
  - " кусь!"
  - " *кусь*"
  - " мур~"
  - " мур-мур~"
  - "..."
  - " бака.."
  - " братик"
  - "~"
  - " хиик~"
  - " хе-хе~"
  - " хи-хи~"
  - " хик-хик~"
  - "!"

emojies:
  - ">,<"
  - ">.<"
  - "uwu"
  - "UwU"
  - "(owo )"
  - "ÚwÚ"
  - "(◡ ሠ ◡)"
  - "( ｡ᵘ ᵕ ᵘ ｡)"
  - "( ͡U ω ͡U )"
  - "(´꒳`)"
  - "(⑅˘꒳˘)"
  - "ʕ•ᴥ•ʔ"
  - "(* ^ ω ^)"
  - "(ﾉ´ з `)ノ"
  - "(＾＾＃)"
  - "⊂(･ω･*⊂)"
  - "(∪｡∪)｡｡｡zzZ"
  - "(－ω－) zzZ"
  - "( ͡° ͜ʖ ͡°)"